const options = [
  'GuestDay Delivery or pickup outside office hours',
  'GuestDay Receptionist',
  'GuestDay Technical Support',
  'GuestDay Technical Support Understudy',
  'GuestDay Delivery + monitor setup or pickup + monitor teardown outside office hours',
  'Class Instructor level 1 (new, assistant)',
  'Class Instructor level 2 (experienced, pair/assistant/secondary)',
  'Class Instructor level 3 (experienced, solo/primary)',
  'Class Instructor level 4 (very experienced)',
  'Class Instructor level 6 (special rate)',
  'Workshop Secondary Instructor',
  'Workshop Primary Instructor',
  'Tinkercademy X Instructor',
  'Grading (per man-day)',
  'Instructional Design - Existing, pre-approved/planned classes',
  'Instructional Design - Brand new classes',
  'Other / Tinkertanker Misc Bonus',
  'Event facilitation',
  'NIE Weather Station Maintenance',
  'Leave Encashment',
];
